name: bryonmccartney
favicon: null
layout_spectrum: 0.5
typography_spectrum: 0.58442
title: Bryon McCartney
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#990000'
    - '#cccccc'
    - '#b17878'
    - '#a83f3f'
    - '#bb9393'
  brandStrength: 0.8125
  lightness: 0.25
  saturation: 0
  rhythmicContrast: 1
purpose: []
