name: bryonmccartney
favicon: null
layout_spectrum: 0.2658230250235647
typography_spectrum: 0.6621334608644247
title: Bryon McCartney
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#2f2f2f'
    - '#5f5f5f'
    - '#b3b3b3'
  brandStrength: 0.75
  lightness: 0.9971745123621076
  saturation: 0.6550644184462726
  rhythmicContrast: 0.6404629957396537
purpose: []
